import { useState } from "react";
import { Navigate, useLocation, useNavigate } from "react-router-dom";
import { useAuth } from "../../context/AuthContext";
import { completeInterview } from "../../services/interviewService";

const questionSets = {
  Behavioral: ["Tell me about a difficult problem you solved.", "Describe a time you received difficult feedback.", "Tell me about a time you worked with conflicting priorities.", "Describe a project you are proud of and your contribution.", "What would you do differently in a past team project?"],
  Technical: ["Walk me through debugging a feature that fails only in production.", "How would you design a scalable notification system?", "Explain a technical decision you made and its trade-offs.", "How do you ensure the quality of your code?", "Describe a challenging technical concept to a non-technical stakeholder."],
  "HR round": ["Tell me about yourself.", "Why are you interested in this role?", "What are your strongest skills and one area you are improving?", "Describe the work environment where you do your best work.", "What questions would you ask the interviewer?"],
};

export default function InterviewSession() {
  const { isAuthenticated, initializing } = useAuth();
  const location = useLocation(); const navigate = useNavigate();
  const { mode = "Behavioral", difficulty = "Balanced", targetRole = "", experienceLevel = "", skills = "", questions: tailoredQuestions } = location.state || {};
  const questions = tailoredQuestions?.length === 5 ? tailoredQuestions : questionSets[mode] || questionSets.Behavioral;
  const [index, setIndex] = useState(0); const [answer, setAnswer] = useState(""); const [responses, setResponses] = useState([]); const [loading, setLoading] = useState(false); const [feedback, setFeedback] = useState(null); const [error, setError] = useState("");
  if (initializing) return null; if (!isAuthenticated) return <Navigate to="/login" replace />;
  const next = async () => {
    if (answer.trim().length < 20) return setError("Write at least a few complete sentences before continuing.");
    const nextResponses = [...responses, { question: questions[index], answer: answer.trim() }]; setResponses(nextResponses); setAnswer(""); setError("");
    if (index < questions.length - 1) return setIndex(index + 1);
    setLoading(true); try { const data = await completeInterview({ mode, difficulty, targetRole, experienceLevel, skills, responses: nextResponses }); setFeedback(data.feedback); } catch (requestError) { setError(requestError.message || "Couldn’t finish the interview review."); } finally { setLoading(false); }
  };
  if (feedback) return <main className="min-h-screen bg-[#F8F7F4] px-5 py-10 text-[#16213d]"><section className="mx-auto max-w-3xl"><p className="text-xs font-bold tracking-[0.14em] text-[#0057FF]">INTERVIEW COMPLETE</p><div className="mt-5 rounded-[24px] bg-[#16213d] p-7 text-white"><p className="text-xs font-bold tracking-[0.13em] text-blue-200">OVERALL SCORE</p><p className="mt-3 font-display text-7xl font-bold">{feedback.overallScore}</p><p className="mt-5 text-sm leading-6 text-slate-300">{feedback.summary}</p></div><div className="mt-5 grid gap-5 md:grid-cols-2"><article className="rounded-[24px] bg-white p-6"><h2 className="font-display text-xl font-bold">What worked</h2><ul className="mt-4 space-y-3">{feedback.strengths.map((item) => <li key={item} className="text-sm text-slate-600">✓ {item}</li>)}</ul></article><article className="rounded-[24px] bg-white p-6"><h2 className="font-display text-xl font-bold">Practice next</h2><ul className="mt-4 space-y-3">{feedback.improvements.map((item) => <li key={item} className="text-sm text-slate-600">→ {item}</li>)}</ul></article></div><button onClick={() => navigate("/dashboard")} className="mt-7 rounded-xl bg-[#0057FF] px-5 py-3 text-sm font-bold text-white">Back to dashboard</button></section></main>;
  return <main className="min-h-screen bg-[#F8F7F4] px-5 py-10 text-[#16213d]"><section className="mx-auto max-w-3xl"><button onClick={() => navigate("/dashboard")} className="text-sm font-bold text-[#0057FF]">← Exit interview</button><p className="mt-8 text-xs font-bold tracking-[0.14em] text-[#0057FF]">{mode.toUpperCase()} · {difficulty.toUpperCase()}</p><div className="mt-4 h-2 overflow-hidden rounded-full bg-slate-200"><div className="h-full rounded-full bg-[#0057FF] transition-all" style={{ width: `${((index + 1) / questions.length) * 100}%` }} /></div><p className="mt-3 text-sm text-slate-500">Question {index + 1} of {questions.length}</p><article className="mt-6 rounded-[24px] bg-white p-6 sm:p-8"><h1 className="font-display text-3xl font-bold leading-snug">{questions[index]}</h1><textarea autoFocus value={answer} onChange={(event) => setAnswer(event.target.value)} maxLength={4000} placeholder="Answer as if you were speaking to the interviewer…" className="mt-7 min-h-52 w-full rounded-xl border border-slate-200 bg-[#FBFAF8] p-4 text-sm leading-6 outline-none focus:border-[#0057FF] focus:ring-4 focus:ring-[#E6EEFF]" /><div className="mt-4 flex items-center justify-between gap-4"><span className="text-xs text-slate-400">{answer.trim() ? `${answer.trim().split(/\s+/).length} words` : "Aim for 60–120 words"}</span><button disabled={loading} onClick={next} className="rounded-xl bg-[#0057FF] px-5 py-3 text-sm font-bold text-white disabled:opacity-60">{loading ? "Preparing feedback…" : index === questions.length - 1 ? "Finish interview" : "Next question"}</button></div>{error && <p className="mt-4 text-sm font-semibold text-[#C63D32]">{error}</p>}</article></section></main>;
}
